services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: neurocurso
    networks:
      - my_network # Certifique-se de que o banco de dados está na rede correta
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    networks:
      - my_network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
