ui:
  models:
    - "gpt-4o-mini"
    - "gpt-4o"
    - "gpt-3.5-turbo"
    - "gpt-4-turbo"
  labels:
    main_title: "Assistente de IA para Cefaleias"
    create_assistant:
      title: "Criar Assistente"
      name: "Nome do Assistente"
      model: "Modelo"
      instructions: "Instruções"
      description: "Descrição"
      user_id: "ID do Usuário"
      create_button: "Criar Assistente"
      clear_button: "Limpar"
      result: "Resultado da Criação"
    send_question:
      title: "Enviar Pergunta"
      assistant_id: "ID do Assistente"
      question: "Pergunta"
      user_id: "ID do Usuário"
      thread_id: "ID da Thread"
      send_button: "Enviar"
      clear_button: "Limpar"
      result: "Resposta do Assistente"
    audio_question:
      title: "Pergunta por Áudio"
      submit_button: "Enviar Áudio"
      text_response: "Transcrição do Áudio"
    create_vector_store:
      title: "Criar/Atualizar Vector Store"
      assistant_id: "ID do Assistente"
      file_paths: "Caminhos dos Arquivos"
      create_button: "Criar/Atualizar"
      clear_button: "Limpar"
      result: "Resultado da Operação"
    list_assistants:
      title: "Listar Assistentes"
      list_button: "Listar"
      result: "Lista de Assistentes"
      limit_label: "Número de Assistentes a Exibir"
      limit_info: "Selecione entre 1 e 99 assistentes (padrão: 20)"
      show_instructions_label: "Exibir Prompt"
      show_instructions_info: ""