ui:
  labels:
    main_title: "# Painel ADMIN Neurocle"
    create_assistant:
      title: "Nova Assistente"
      name: "Nome da Assistente"
      model: "Modelod"
      instructions: "Instruções"
      description: "Descrição"
      user_id: "ID do Usuário"
      create_button: "Criar Assistente"
      clear_button: "Limpar Formulário"
      result: "Resultado da Criação do Assistente"
    send_question:
      title: "Enviar Pergunta"
      assistant_id: "ID do Assistente"
      question: "Pergunta"
      user_id: "ID do Usuário"
      thread_id: "ID da Conversa (thread_id existente | 'create')"
      send_button: "Enviar Pergunta"
      clear_button: "Limpar Formulário"
      result: "Resposta da Pergunta"
    create_vector_store:
      title: "Criar Armazenamento de Vetores"
      assistant_id: "ID do Assistente"
      file_paths: "Caminhos dos Arquivos (separados por vírgula)"
      create_button: "Criar Armazenamento de Vetores"
      clear_button: "Limpar Formulário"
      result: "Resultado da Criação do Armazenamento de Vetores"
    list_assistants:
      title: "Listar Assistentes"
      list_button: "Listar Assistentes"
      result: "Lista de Assistentes"
  models:
    - "gpt-4o-mini"
    - "gpt-3.5-turbo"
    - "gpt-4o"
    - "gpt-4o-turbo"
    - "gpt-o1-preview"
    - "gpt-o1-mini"